"""add_is_visible_to_motions

Revision ID: 0e7439a74cb6
Revises: b4e05d2de67f
Create Date: 2026-03-18 23:19:43.256056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7439a74cb6'
down_revision: Union[str, Sequence[str], None] = 'b4e05d2de67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motions', sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motions', 'is_visible')
    # ### end Alembic commands ###
