"""add lot_proxy table and ballot_submission proxy_email

Revision ID: c8337fb36d23
Revises: a1b2c3d4e5f6
Create Date: 2026-03-12 18:24:26.821051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8337fb36d23'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot_proxies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lot_owner_id', sa.Uuid(), nullable=False),
    sa.Column('proxy_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_owner_id'], ['lot_owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_owner_id', name='uq_lot_proxies_lot_owner_id')
    )
    op.create_index('ix_lot_proxies_proxy_email', 'lot_proxies', ['proxy_email'], unique=False)
    op.add_column('ballot_submissions', sa.Column('proxy_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ballot_submissions', 'proxy_email')
    op.drop_index('ix_lot_proxies_proxy_email', table_name='lot_proxies')
    op.drop_table('lot_proxies')
    # ### end Alembic commands ###
