"""initial_schema

Revision ID: dcb854233f78
Revises: 
Create Date: 2026-03-09 13:45:26.140031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb854233f78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manager_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='agmstatus'), server_default='open', nullable=False),
    sa.Column('meeting_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voting_closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('voting_closes_at > meeting_at', name='ck_agm_voting_closes_after_meeting'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot_owners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('lot_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('unit_entitlement', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('unit_entitlement >= 0', name='ck_lot_owners_entitlement_nonneg'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'lot_number', name='uq_lot_owners_building_lot')
    )
    op.create_table('agm_lot_weights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agm_id', sa.Uuid(), nullable=False),
    sa.Column('lot_owner_id', sa.Uuid(), nullable=False),
    sa.Column('voter_email', sa.String(), nullable=False),
    sa.Column('unit_entitlement_snapshot', sa.Integer(), nullable=False),
    sa.CheckConstraint('unit_entitlement_snapshot >= 0', name='ck_agm_lot_weights_entitlement_nonneg'),
    sa.ForeignKeyConstraint(['agm_id'], ['agms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_owner_id'], ['lot_owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agm_id', 'lot_owner_id', name='uq_agm_lot_weights_agm_lot')
    )
    op.create_table('ballot_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agm_id', sa.Uuid(), nullable=False),
    sa.Column('voter_email', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agm_id'], ['agms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agm_id', 'voter_email', name='uq_ballot_submissions_agm_voter')
    )
    op.create_table('email_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agm_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'delivered', 'failed', name='emaildeliverystatus'), server_default='pending', nullable=False),
    sa.Column('total_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agm_id'], ['agms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agm_id')
    )
    op.create_table('motions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agm_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agm_id'], ['agms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agm_id', 'order_index', name='uq_motions_agm_order')
    )
    op.create_table('session_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('voter_email', sa.String(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('agm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agm_id'], ['agms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agm_id', sa.Uuid(), nullable=False),
    sa.Column('motion_id', sa.Uuid(), nullable=False),
    sa.Column('voter_email', sa.String(), nullable=False),
    sa.Column('choice', sa.Enum('yes', 'no', 'abstained', name='votechoice'), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', name='votestatus'), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agm_id'], ['agms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motion_id'], ['motions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agm_id', 'motion_id', 'voter_email', name='uq_votes_agm_motion_voter')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('session_records')
    op.drop_table('motions')
    op.drop_table('email_deliveries')
    op.drop_table('ballot_submissions')
    op.drop_table('agm_lot_weights')
    op.drop_table('lot_owners')
    op.drop_table('agms')
    op.drop_table('buildings')
    # ### end Alembic commands ###
